### ISSUE TITLE
Comment Submission Form Placement

### ISSUE THREAD

**Issue by madranet** [posativ/isso#304] opened 2017-02-19 20:16 UTC
Is there a way to config Isso to place the comment entry form *after* any existing comments instead of before?  If not, could this be added as an option? 

It makes more sense to me for the page flow to be:

`Read content > Read others' comments > Add comment`

rather than 

`Read content > Add comment  > Read others' comments`

which makes it more likely that people will add a comment making a point that's already been made.

**Comment by zaygraveyard** [comment] 2017-03-02 14:11
Possible duplicate of #294

**Comment by blatinier** [comment] 2017-09-01 22:06
Yop closing.

**Closed by blatinier** 2017-09-01 22:06 UTC
