### ISSUE TITLE
__init__.py tries to import class SharedDataMiddleware from a wrong module

### ISSUE THREAD

**Issue by babakRz63ai** [posativ/isso#641] opened 2020-04-17 16:29 UTC
I installed isso on a CentOS 8 machine using PyPi for Python 3.6, and following instructions on the website, in a virtual environment in `/opt/isso`. Now when I want to start isso, it displays this stack trace and exits:

```
Traceback (most recent call last):
  File "./isso", line 5, in <module>
    from isso import main
  File "/opt/isso/lib/python3.6/site-packages/isso/__init__.py", line 60, in <module>
    from werkzeug.wsgi import SharedDataMiddleware
ImportError: cannot import name 'SharedDataMiddleware'
```

I've noticed there is no `SharedDataMiddleware` class in `/opt/isso/lib/python3.6/site-packages/werkzeug/wsgi.py` but this class indeed sits in `/opt/isso/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py`.

These are versions of python and pip in the virtual environment:
```
Python 3.6.8
pip 20.0.2 from /opt/isso/lib/python3.6/site-packages/pip (python 3.6)
```
And this is version of `werkzeug` found in its` __init__.py` : `__version__ = "1.0.1"`

**Comment by jelmer** [comment] 2020-04-17 16:37
Thanks for the report - this is a dupe of #617.

**Closed by jelmer** 2020-04-17 16:37 UTC
