### ISSUE TITLE
`cgi.escape` is deprecated and removed in Python 3.8

### ISSUE THREAD

**Issue by BookGin** [posativ/isso#603] opened 2019-12-28 09:01 UTC
```
Traceback (most recent call last):                                                                                             
  File "/home/user/.local/lib/python3.8/site-packages/isso/__init__.py", line 141, in dispatch                                 
    response = handler(request.environ, request, **values)     
  File "/home/user/.local/lib/python3.8/site-packages/isso/views/comments.py", line 92, in dec                                 
    return func(self, env, req, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/isso/views/__init__.py", line 46, in dec                                 
    return func(cls, env, req, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/isso/views/comments.py", line 263, in new
    data[field] = cgi.escape(data[field])
AttributeError: module 'cgi' has no attribute 'escape'
```

The error can be reproduced for posting a comment with an non-empty name.

`cgi.escape` seems to be removed in [Python 3.8](https://docs.python.org/3.7/library/cgi.html#cgi.escape). Use `html.escape` instead.

A workaround:

```
sed -i 's/cgi/html/g' /home/user/.local/lib/python3.8/site-packages/isso/views/comments.py
```

**Comment by tirkarthi** [comment] 2020-01-04 07:57
Seems like a duplicate of https://github.com/posativ/isso/issues/599

**Closed** 2020-02-15 15:11 UTC
