### ISSUE TITLE
Link Restriction

### ISSUE THREAD

**Issue by Cavain** [posativ/isso#408] opened 2018-04-02 15:02 UTC
Hello,

How can we restrict people from putting their links in comment section?

Thanks for this incredible comment section.

**Comment by blatinier** [comment] 2018-04-04 16:27
It's not possible for the moment. You can allow more html tag but not disallow the default ones.
Do you want to prevent links because of SEO effect and resulting spam? In which case you need goes along with #373

**Comment by ix5** [comment] 2021-12-27 01:08
Duplicate of https://github.com/posativ/isso/issues/751

**Closed by ix5** 2021-12-27 01:08 UTC
Labels: question
