### ISSUE TITLE
Feature request: Reverse-sort the comments on rendering (latest first)

### ISSUE THREAD

**Issue by PeterCxy** [posativ/isso#319] opened 2017-04-15 13:05 UTC
It's not very important, but I do think that sorting comments in 'latest-first' order will be more natural for readers. Maybe an option 'data-isso-sorting' can be added to the JavaScript client.

**Comment by dbrgn** [comment] 2017-04-22 16:36
I agree. Seems to be a duplicate of #4.

**Comment by blatinier** [comment] 2017-09-02 12:40
Agree. Closing. @jelmer I add the label feature to #4

**Closed by blatinier** 2017-09-02 12:40 UTC
Labels: feature
