### ISSUE TITLE
How to set the order of the comments?

### ISSUE THREAD

**Issue by SnorlaxYum** [posativ/isso#265] opened 2016-08-13 08:01 UTC
Generally, the newest is on the bottom.  
Instead I want the newest to be on the top, how to do it?

**Comment by tanhaogg** [comment] 2017-01-05 05:06
I also think it should be an important option.

**Comment by dbrgn** [comment] 2017-04-22 16:36
Duplicate of #4.

**Comment by blatinier** [comment] 2017-09-02 12:39
Yop as @dbrgn said. duplicated.

**Closed by blatinier** 2017-09-02 12:39 UTC
