### ISSUE TITLE
Modify the action attribution of the form on `/admin` page.

### ISSUE THREAD

**Issue by Losses** [posativ/isso#576] opened 2019-10-05 14:22 UTC
It's really a strange behavior that hard code the submit path to 

```
http://example.com/login
```

if we set it to

```
//example.com/login
```

The admin panel will support HTTPS and won't be troubled by 304 redirect.

or what we could do further, just remove `http:` from `isso_host_script` only leave `//example.com/xxxx`, which may not break anything

**Comment by jelmer** [comment] 2019-10-05 14:45
A patch to fix this would be great.

**Comment by ix5** [comment] 2019-12-28 20:06
Where do you see `http` hardcoded here? https://github.com/posativ/isso/blob/5655f194b311c50126713e6f40440e7f89be6479/isso/views/comments.py#L1085-L1105

**Comment by ix5** [comment] 2021-12-31 22:38
Did you set `public-endpoint` to an HTTP URI? Try changing it to `https` instead, that's what Isso will then use internally.

@Losses Would could please verify your issue persists on a current Isso installation with the change to public-endpoint?

**Comment by ix5** [comment] 2021-12-31 22:40
Most likely a duplicate of https://github.com/posativ/isso/issues/576, closing in favour of discussions there

**Closed by ix5** 2021-12-31 22:40 UTC
Labels: support, question, needs-more-info
