### ISSUE TITLE
:invalid style for email input is not shown

### ISSUE THREAD

**Issue by m-cat** [posativ/isso#441] opened 2018-05-09 07:07 UTC
Was playing with the cute little demo on the Isso page when I went and I put `asdf` as the email. Clicking "submit" did nothing, but there was no indication that the email input was invalid (I tested on Firefox, it does not accept `asdf` for an input of `type='email'`). I believe you must have overriden the `box-shadow` css attribute which is used by default (at least in Firefox) to highlight invalid fields.

I guess the intention might be to let the client display an error message in this case using JS or something? It should still be up to the user whether they want to override the `:invalid` style.

Edit: actually, it appears that the website field is the culprit. Seems backwards haha, I would verify the email but not the website, which can just be "google" or something.

**Comment by ix5** [comment] 2022-02-10 20:29
@m-cat would you mind submitting a PR that fixes the behavior?

**Comment by m-cat** [comment] 2022-02-11 23:45
> @m-cat would you mind submitting a PR that fixes the behavior?

Certainly. My rate is $200/hour. For this particular project I would require a $100 up-front payment, as it does not seem too involved. Please write to the email provided on my profile with further inquiries. Thank you.

**Comment by ix5** [comment] 2022-02-12 13:31
Thank you for your offer. Funding is a major problem in the FLOSS world. I am afraid there is currently no process of raising or distributing funds associated with this project and I am not aware of any efforts to create one.

Speaking for myself, I am also not interested enough to "contribute" to "fix" this "issue".
However, if anyone feels like they need to financially support **_you_** to fix a something that is a minor annoyance **_to you_**, I'll be the last to object.

As this is mostly a duplicate of https://github.com/posativ/isso/issues/673, I'm going to close this issue.

**Closed by ix5** 2022-02-12 13:31 UTC
Labels: needs-contributor, client
