### ISSUE TITLE
Spacing between paragraphs

### ISSUE THREAD

**Issue by Fastidious** [posativ/isso#149] opened 2015-01-07 10:56 UTC
Right now lines between paragraphs are been stripped. I understand more than one line it should, but allowing paragraph separation, like this:

Should be allowed. It really doesn't make sense the way it behaves right now.

**Comment by posativ** [comment] 2015-01-07 11:14
Duplicate of https://github.com/posativ/isso/issues/145. It makes sense if you know Markdown, but I'll add an option to break on newlines (in addition to paragraphs).

**Closed by posativ** 2015-01-07 11:14 UTC
