### ISSUE TITLE
Possible to have non local database?

### ISSUE THREAD

**Issue by mrchief** [posativ/isso#239] opened 2016-03-03 21:51 UTC
Instead of using local SQLite DB, is it possible to point it to a remote database?

**Comment by posativ** [comment] 2016-03-04 10:30
Not yet.

**Comment by mishra-avinash** [comment] 2021-02-12 14:55
do we have this feature now? I want to point it to the RDS database. Is it possible now?

**Comment by ix5** [comment] 2021-12-26 22:36
Duplicate of https://github.com/posativ/isso/issues/205, more fruitful discussion there.

**Closed by ix5** 2021-12-26 22:36 UTC
