### ISSUE TITLE
admin panel not working

### ISSUE THREAD

**Issue by Swuap1** [posativ/isso#539] opened 2019-02-28 06:59 UTC
I got this set in my conf file but when I go to commentrs.domain.com/admin it brings me to my site.

[admin]
enabled = true
password = password

**Comment by jelmer** [comment] 2019-02-28 07:26
What version of isso are you running?

**Comment by Swuap1** [comment] 2019-02-28 19:01
The latest, just installed it.

**Comment by jelmer** [comment] 2019-02-28 22:39
So that's 0.12.2?

What does it do exactly, does it redirect you or just serve you the main page?

**Comment by Swuap1** [comment] 2019-03-01 00:23
Yes.

redirects me to my site when I go commentrs.domain.com/admin. 

my nginx config
> server {
>     listen [::]:80 default ipv6only=off;
>     server_name example.tld;
>     root ...;
> }
> 
> server {
>     listen [::]:80;
>     server_name comments.example.tld;
> 
>     location / {
>         proxy_pass http://localhost:8080;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
>     }
> }

**Comment by jelmer** [comment] 2019-03-01 00:45
That's odd - you should be seeing a page explaining the admin interface is disabled if the configuration is incorrect. Otherwise you should at the very least get a login page. Do other non-index isso pages work?

**Comment by Swuap1** [comment] 2019-03-01 04:39
Think I solved it.
 
Since I have both the comments and site domain pointed to the same IP, I use Wordpress and when I go to comments.domain.com/admin it redirects to my site.com/admin the Wordpress login. 

The nginx config im using is from the Isso quickstart guide, I don't get it.

**Comment by matolivier** [comment] 2019-07-31 07:28
Hi, as your wordpress domain is the default one, I suspect you misstyped comments.exemple.tld either in nginx conf, either in your web browser (thus nginx redirects you to wordpress conf).

**Comment by ix5** [comment] 2021-12-31 23:21
@Swuap1 would you kindly confirm that your issue wasn't caused by what @matolivier suggested?
Otherwise I'll be closing this.

**Closed** 2022-02-10 20:20 UTC
Labels: support, needs-more-info
